### ISSUE TITLE
Bug in EDPluginControlDozorv1_0: no valid convert

### ISSUE THREAD

**Issue by jordiandreu** [olofsvensson/edna-mx#22]
The Dozor plugin (EDPluginControlDozorv1_0.py) fails to parse spot file leading to the following error:

> 20180921-124119   Traceback (most recent call last): 
> 20180921-124119    File "/mnt/hpcsoftware/bl13/edna-mx-devel/kernel/src/EDAction.py", line 111, in executeKernel 
> 20180921-124119      self.process() 
> 20180921-124119    File "/mnt/hpcsoftware/bl13/edna-mx-devel/mxv1/plugins/EDPluginControlDozor-v1.0/plugins/EDPluginControlDozorv1_0.py", line 254, in proce
>  ss 
> 20180921-124119      numpyArray = numpy.loadtxt(spotFile, skiprows=3) 
> 20180921-124119    File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 827, in loadtxt 
> 20180921-124119      items = [conv(val) for (conv, val) in zip(converters, vals)] 
> 20180921-124119  ValueError: could not convert string to float: *******

SpotFile:

> ../EDApplication_20180921-124112/ControlInterfaceToMXCuBEv1_3/ControlInterfacev1_2/Characterisation/Indexing/ControlImageQualityIndicatorsv1_5/ControlDozor_ref-testvic_5_0001/Dozor_00001/00001.spot

The spotFile contains ******* values in its columns and they cannot be converted using the _numpy.loadtxt_ method. A workaround would be to replace this method by the _genfromtxt_ which allows to exclude certain string from the conversion.

However, the root of the error is in the spotFile. The file format recorder seems to not be able to write values larger than 99999.9 into the spotFile columns. Is is possible to change the format for the spotFile column values?

**Comment by olofsvensson** [comment]
Thanks for this feedback! Would it be possible for you to send me the spot file that created this issue? Also, which version Dozor are you using?

**Comment by jordiandreu** [comment]
Hi Olof,
The Dozor version is:

>  Program dozor /A.Popov & G.Bourenkov/
>  Version 1.3.1 //  03.12.2014
>  Copyright 2014 by Alexander Popov and Gleb Bourenkov

Find attached the spot file:
[00001.spot.txt](https://github.com/olofsvensson/edna-mx/files/2427548/00001.spot.txt)
